global:
  scrape_interval: 5s  # Intervalo para hacer scraping de métricas

scrape_configs:
  - job_name: 'memory-optimization-container-v1'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['memory-optimization-container-v1:8080']
  - job_name: 'memory-optimization-container-v2'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['memory-optimization-container-v2:8080']